-- ========================================
-- TABELA USERS
-- ========================================
CREATE TABLE users (
                       cd_usuario      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nm_usuario      VARCHAR(120),
                       ds_email        VARCHAR(120) UNIQUE,
                       ds_login        VARCHAR(80) UNIQUE,
                       ds_senha_hash   VARCHAR(255) NOT NULL,
                       st_ativo        BOOLEAN NOT NULL DEFAULT TRUE,
                       tp_usuario      SMALLINT,
                       dt_cadastro     TIMESTAMP NOT NULL DEFAULT NOW()
);
-- ========================================
-- TABELA PACIENTE
-- ========================================
CREATE TABLE paciente (
                          cd_paciente     BIGSERIAL PRIMARY KEY,
                          nm_paciente     VARCHAR(150) NOT NULL,
                          nr_cpf          VARCHAR(14),
                          dt_nascimento   TIMESTAMP,
                          nr_telefone     VARCHAR(30),
                          ds_email        VARCHAR(120),
                          ds_endereco     VARCHAR(255),
                          ds_observacao   TEXT,
                          st_ativo        BOOLEAN NOT NULL DEFAULT TRUE,
                          dt_cadastro     TIMESTAMP NOT NULL DEFAULT NOW()
);